#############################################################################
# Makefile for building: QAF
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  QAF.pro
# Template: subdirs
# Command: C:\Qt\Qt5.7.0\5.7\msvc2013\bin\qmake.exe -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile QAF.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\Qt5.7.0\5.7\msvc2013\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src-NetWork-NetWork-pro \
		sub-src-DBManager-DBManager-pro \
		sub-src-QtAwesome-QtAwesome-pro \
		sub-src-QtCommonModel-QtCommonModel-pro \
		sub-src-Utils-Utils-pro \
		sub-src-QAFCore-QAFCore-pro \
		sub-src-QAF-QAF-pro \
		sub-src-UIPlugin-UIPlugin-pro \
		sub-src-tests-testNetWork-testNetWork-pro \
		sub-src-examples-testPlugin-testPlugin-pro


sub-src-NetWork-NetWork-pro-qmake_all:  FORCE
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	cd src\NetWork\ && $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && $(MAKE) -f Makefile qmake_all
sub-src-NetWork-NetWork-pro: FORCE
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-NetWork-NetWork-pro-make_first: FORCE
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-NetWork-NetWork-pro-all: FORCE
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-NetWork-NetWork-pro-clean: FORCE
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-NetWork-NetWork-pro-distclean: FORCE
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-NetWork-NetWork-pro-install_subtargets: FORCE
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-NetWork-NetWork-pro-uninstall_subtargets: FORCE
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-DBManager-DBManager-pro-qmake_all:  FORCE
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	cd src\DBManager\ && $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && $(MAKE) -f Makefile qmake_all
sub-src-DBManager-DBManager-pro: FORCE
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-DBManager-DBManager-pro-make_first: FORCE
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-DBManager-DBManager-pro-all: FORCE
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-DBManager-DBManager-pro-clean: FORCE
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-DBManager-DBManager-pro-distclean: FORCE
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-DBManager-DBManager-pro-install_subtargets: FORCE
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-DBManager-DBManager-pro-uninstall_subtargets: FORCE
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtAwesome-QtAwesome-pro-qmake_all:  FORCE
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	cd src\QtAwesome\ && $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && $(MAKE) -f Makefile qmake_all
sub-src-QtAwesome-QtAwesome-pro: FORCE
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtAwesome-QtAwesome-pro-make_first: FORCE
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtAwesome-QtAwesome-pro-all: FORCE
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtAwesome-QtAwesome-pro-clean: FORCE
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtAwesome-QtAwesome-pro-distclean: FORCE
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtAwesome-QtAwesome-pro-install_subtargets: FORCE
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtAwesome-QtAwesome-pro-uninstall_subtargets: FORCE
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtCommonModel-QtCommonModel-pro-qmake_all:  FORCE
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	cd src\QtCommonModel\ && $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && $(MAKE) -f Makefile qmake_all
sub-src-QtCommonModel-QtCommonModel-pro: FORCE
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtCommonModel-QtCommonModel-pro-make_first: FORCE
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtCommonModel-QtCommonModel-pro-all: FORCE
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtCommonModel-QtCommonModel-pro-clean: FORCE
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtCommonModel-QtCommonModel-pro-distclean: FORCE
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtCommonModel-QtCommonModel-pro-install_subtargets: FORCE
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtCommonModel-QtCommonModel-pro-uninstall_subtargets: FORCE
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-Utils-Utils-pro-qmake_all:  FORCE
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	cd src\Utils\ && $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && $(MAKE) -f Makefile qmake_all
sub-src-Utils-Utils-pro: FORCE
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-Utils-Utils-pro-make_first: FORCE
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-Utils-Utils-pro-all: FORCE
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-Utils-Utils-pro-clean: FORCE
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-Utils-Utils-pro-distclean: FORCE
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-Utils-Utils-pro-install_subtargets: FORCE
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-Utils-Utils-pro-uninstall_subtargets: FORCE
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QAFCore-QAFCore-pro-qmake_all:  FORCE
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	cd src\QAFCore\ && $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && $(MAKE) -f Makefile qmake_all
sub-src-QAFCore-QAFCore-pro: FORCE
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-QAFCore-QAFCore-pro-make_first: FORCE
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QAFCore-QAFCore-pro-all: FORCE
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QAFCore-QAFCore-pro-clean: FORCE
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QAFCore-QAFCore-pro-distclean: FORCE
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QAFCore-QAFCore-pro-install_subtargets: FORCE
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QAFCore-QAFCore-pro-uninstall_subtargets: FORCE
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QAF-QAF-pro-qmake_all:  FORCE
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	cd src\QAF\ && $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && $(MAKE) -f Makefile qmake_all
sub-src-QAF-QAF-pro: FORCE
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-QAF-QAF-pro-make_first: FORCE
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QAF-QAF-pro-all: FORCE
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QAF-QAF-pro-clean: FORCE
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QAF-QAF-pro-distclean: FORCE
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QAF-QAF-pro-install_subtargets: FORCE
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QAF-QAF-pro-uninstall_subtargets: FORCE
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-UIPlugin-UIPlugin-pro-qmake_all:  FORCE
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	cd src\UIPlugin\ && $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && $(MAKE) -f Makefile qmake_all
sub-src-UIPlugin-UIPlugin-pro: FORCE
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-UIPlugin-UIPlugin-pro-make_first: FORCE
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-UIPlugin-UIPlugin-pro-all: FORCE
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-UIPlugin-UIPlugin-pro-clean: FORCE
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-UIPlugin-UIPlugin-pro-distclean: FORCE
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-UIPlugin-UIPlugin-pro-install_subtargets: FORCE
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-UIPlugin-UIPlugin-pro-uninstall_subtargets: FORCE
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-tests-testNetWork-testNetWork-pro-qmake_all:  FORCE
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	cd src\tests\testNetWork\ && $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && $(MAKE) -f Makefile qmake_all
sub-src-tests-testNetWork-testNetWork-pro: FORCE
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-tests-testNetWork-testNetWork-pro-make_first: FORCE
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-tests-testNetWork-testNetWork-pro-all: FORCE
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-tests-testNetWork-testNetWork-pro-clean: FORCE
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-tests-testNetWork-testNetWork-pro-distclean: FORCE
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-tests-testNetWork-testNetWork-pro-install_subtargets: FORCE
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-tests-testNetWork-testNetWork-pro-uninstall_subtargets: FORCE
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-examples-testPlugin-testPlugin-pro-qmake_all:  FORCE
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	cd src\examples\testPlugin\ && $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && $(MAKE) -f Makefile qmake_all
sub-src-examples-testPlugin-testPlugin-pro: FORCE
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-src-examples-testPlugin-testPlugin-pro-make_first: FORCE
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-src-examples-testPlugin-testPlugin-pro-all: FORCE
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-src-examples-testPlugin-testPlugin-pro-clean: FORCE
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-examples-testPlugin-testPlugin-pro-distclean: FORCE
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-examples-testPlugin-testPlugin-pro-install_subtargets: FORCE
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-src-examples-testPlugin-testPlugin-pro-uninstall_subtargets: FORCE
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: QAF.pro C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\win32-msvc2013\qmake.conf C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\spec_pre.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\common\angle.conf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\common\msvc-base.conf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\common\msvc-desktop.conf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\qconfig.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_charts.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_charts_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_datavisualization.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_datavisualization_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_purchasing.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_purchasing_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_script_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webengine.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webengine_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\qt_functions.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\qt_config.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\win32\qt_config.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\win32-msvc2013\qmake.conf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\spec_post.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\exclusive_builds.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\default_pre.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\win32\default_pre.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\resolve_config.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\default_post.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\qml_debug.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\win32\rtti.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\precompile_header.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\warn_on.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\file_copies.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\win32\windows.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\testcase_targets.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\exceptions.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\yacc.prf \
		C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\lex.prf \
		QAF.pro
	$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile QAF.pro
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\spec_pre.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\common\angle.conf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\common\msvc-base.conf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\common\msvc-desktop.conf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\qconfig.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_charts.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_charts_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_core.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_datavisualization.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_datavisualization_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_help.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_location.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_network.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_purchasing.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_purchasing_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_script.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webengine.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webengine_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\qt_functions.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\qt_config.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\win32\qt_config.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\win32-msvc2013\qmake.conf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\spec_post.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\exclusive_builds.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\default_pre.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\win32\default_pre.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\resolve_config.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\default_post.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\qml_debug.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\win32\rtti.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\precompile_header.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\warn_on.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\file_copies.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\win32\windows.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\testcase_targets.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\exceptions.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\yacc.prf:
C:\Qt\Qt5.7.0\5.7\msvc2013\mkspecs\features\lex.prf:
QAF.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile QAF.pro

qmake_all: sub-src-NetWork-NetWork-pro-qmake_all sub-src-DBManager-DBManager-pro-qmake_all sub-src-QtAwesome-QtAwesome-pro-qmake_all sub-src-QtCommonModel-QtCommonModel-pro-qmake_all sub-src-Utils-Utils-pro-qmake_all sub-src-QAFCore-QAFCore-pro-qmake_all sub-src-QAF-QAF-pro-qmake_all sub-src-UIPlugin-UIPlugin-pro-qmake_all sub-src-tests-testNetWork-testNetWork-pro-qmake_all sub-src-examples-testPlugin-testPlugin-pro-qmake_all FORCE

make_first: sub-src-NetWork-NetWork-pro-make_first sub-src-DBManager-DBManager-pro-make_first sub-src-QtAwesome-QtAwesome-pro-make_first sub-src-QtCommonModel-QtCommonModel-pro-make_first sub-src-Utils-Utils-pro-make_first sub-src-QAFCore-QAFCore-pro-make_first sub-src-QAF-QAF-pro-make_first sub-src-UIPlugin-UIPlugin-pro-make_first sub-src-tests-testNetWork-testNetWork-pro-make_first sub-src-examples-testPlugin-testPlugin-pro-make_first  FORCE
all: sub-src-NetWork-NetWork-pro-all sub-src-DBManager-DBManager-pro-all sub-src-QtAwesome-QtAwesome-pro-all sub-src-QtCommonModel-QtCommonModel-pro-all sub-src-Utils-Utils-pro-all sub-src-QAFCore-QAFCore-pro-all sub-src-QAF-QAF-pro-all sub-src-UIPlugin-UIPlugin-pro-all sub-src-tests-testNetWork-testNetWork-pro-all sub-src-examples-testPlugin-testPlugin-pro-all  FORCE
clean: sub-src-NetWork-NetWork-pro-clean sub-src-DBManager-DBManager-pro-clean sub-src-QtAwesome-QtAwesome-pro-clean sub-src-QtCommonModel-QtCommonModel-pro-clean sub-src-Utils-Utils-pro-clean sub-src-QAFCore-QAFCore-pro-clean sub-src-QAF-QAF-pro-clean sub-src-UIPlugin-UIPlugin-pro-clean sub-src-tests-testNetWork-testNetWork-pro-clean sub-src-examples-testPlugin-testPlugin-pro-clean  FORCE
distclean: sub-src-NetWork-NetWork-pro-distclean sub-src-DBManager-DBManager-pro-distclean sub-src-QtAwesome-QtAwesome-pro-distclean sub-src-QtCommonModel-QtCommonModel-pro-distclean sub-src-Utils-Utils-pro-distclean sub-src-QAFCore-QAFCore-pro-distclean sub-src-QAF-QAF-pro-distclean sub-src-UIPlugin-UIPlugin-pro-distclean sub-src-tests-testNetWork-testNetWork-pro-distclean sub-src-examples-testPlugin-testPlugin-pro-distclean  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-NetWork-NetWork-pro-install_subtargets sub-src-DBManager-DBManager-pro-install_subtargets sub-src-QtAwesome-QtAwesome-pro-install_subtargets sub-src-QtCommonModel-QtCommonModel-pro-install_subtargets sub-src-Utils-Utils-pro-install_subtargets sub-src-QAFCore-QAFCore-pro-install_subtargets sub-src-QAF-QAF-pro-install_subtargets sub-src-UIPlugin-UIPlugin-pro-install_subtargets sub-src-tests-testNetWork-testNetWork-pro-install_subtargets sub-src-examples-testPlugin-testPlugin-pro-install_subtargets FORCE
uninstall_subtargets: sub-src-NetWork-NetWork-pro-uninstall_subtargets sub-src-DBManager-DBManager-pro-uninstall_subtargets sub-src-QtAwesome-QtAwesome-pro-uninstall_subtargets sub-src-QtCommonModel-QtCommonModel-pro-uninstall_subtargets sub-src-Utils-Utils-pro-uninstall_subtargets sub-src-QAFCore-QAFCore-pro-uninstall_subtargets sub-src-QAF-QAF-pro-uninstall_subtargets sub-src-UIPlugin-UIPlugin-pro-uninstall_subtargets sub-src-tests-testNetWork-testNetWork-pro-uninstall_subtargets sub-src-examples-testPlugin-testPlugin-pro-uninstall_subtargets FORCE

sub-src-NetWork-NetWork-pro-debug:
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-DBManager-DBManager-pro-debug:
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-QtAwesome-QtAwesome-pro-debug:
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-QtCommonModel-QtCommonModel-pro-debug:
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-Utils-Utils-pro-debug:
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-QAFCore-QAFCore-pro-debug:
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-QAF-QAF-pro-debug:
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-UIPlugin-UIPlugin-pro-debug:
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-tests-testNetWork-testNetWork-pro-debug:
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-src-examples-testPlugin-testPlugin-pro-debug:
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-src-NetWork-NetWork-pro-debug sub-src-DBManager-DBManager-pro-debug sub-src-QtAwesome-QtAwesome-pro-debug sub-src-QtCommonModel-QtCommonModel-pro-debug sub-src-Utils-Utils-pro-debug sub-src-QAFCore-QAFCore-pro-debug sub-src-QAF-QAF-pro-debug sub-src-UIPlugin-UIPlugin-pro-debug sub-src-tests-testNetWork-testNetWork-pro-debug sub-src-examples-testPlugin-testPlugin-pro-debug

sub-src-NetWork-NetWork-pro-release:
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-DBManager-DBManager-pro-release:
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-QtAwesome-QtAwesome-pro-release:
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-QtCommonModel-QtCommonModel-pro-release:
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-Utils-Utils-pro-release:
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-QAFCore-QAFCore-pro-release:
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-QAF-QAF-pro-release:
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-UIPlugin-UIPlugin-pro-release:
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-tests-testNetWork-testNetWork-pro-release:
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-src-examples-testPlugin-testPlugin-pro-release:
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
release: sub-src-NetWork-NetWork-pro-release sub-src-DBManager-DBManager-pro-release sub-src-QtAwesome-QtAwesome-pro-release sub-src-QtCommonModel-QtCommonModel-pro-release sub-src-Utils-Utils-pro-release sub-src-QAFCore-QAFCore-pro-release sub-src-QAF-QAF-pro-release sub-src-UIPlugin-UIPlugin-pro-release sub-src-tests-testNetWork-testNetWork-pro-release sub-src-examples-testPlugin-testPlugin-pro-release

sub-src-NetWork-NetWork-pro-check:
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-DBManager-DBManager-pro-check:
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtAwesome-QtAwesome-pro-check:
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtCommonModel-QtCommonModel-pro-check:
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-Utils-Utils-pro-check:
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QAFCore-QAFCore-pro-check:
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QAF-QAF-pro-check:
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-UIPlugin-UIPlugin-pro-check:
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-tests-testNetWork-testNetWork-pro-check:
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-src-examples-testPlugin-testPlugin-pro-check:
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-NetWork-NetWork-pro-check sub-src-DBManager-DBManager-pro-check sub-src-QtAwesome-QtAwesome-pro-check sub-src-QtCommonModel-QtCommonModel-pro-check sub-src-Utils-Utils-pro-check sub-src-QAFCore-QAFCore-pro-check sub-src-QAF-QAF-pro-check sub-src-UIPlugin-UIPlugin-pro-check sub-src-tests-testNetWork-testNetWork-pro-check sub-src-examples-testPlugin-testPlugin-pro-check

sub-src-NetWork-NetWork-pro-benchmark:
	@if not exist src\NetWork\ mkdir src\NetWork\ & if not exist src\NetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\NetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\NetWork\NetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-DBManager-DBManager-pro-benchmark:
	@if not exist src\DBManager\ mkdir src\DBManager\ & if not exist src\DBManager\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\DBManager\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\DBManager\DBManager.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-QtAwesome-QtAwesome-pro-benchmark:
	@if not exist src\QtAwesome\ mkdir src\QtAwesome\ & if not exist src\QtAwesome\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtAwesome\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtAwesome\QtAwesome.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-QtCommonModel-QtCommonModel-pro-benchmark:
	@if not exist src\QtCommonModel\ mkdir src\QtCommonModel\ & if not exist src\QtCommonModel\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QtCommonModel\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QtCommonModel\QtCommonModel.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-Utils-Utils-pro-benchmark:
	@if not exist src\Utils\ mkdir src\Utils\ & if not exist src\Utils\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\Utils\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\Utils\Utils.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-QAFCore-QAFCore-pro-benchmark:
	@if not exist src\QAFCore\ mkdir src\QAFCore\ & if not exist src\QAFCore\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAFCore\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAFCore\QAFCore.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-QAF-QAF-pro-benchmark:
	@if not exist src\QAF\ mkdir src\QAF\ & if not exist src\QAF\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\QAF\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\QAF\QAF.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-UIPlugin-UIPlugin-pro-benchmark:
	@if not exist src\UIPlugin\ mkdir src\UIPlugin\ & if not exist src\UIPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\UIPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\UIPlugin\UIPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-tests-testNetWork-testNetWork-pro-benchmark:
	@if not exist src\tests\testNetWork\ mkdir src\tests\testNetWork\ & if not exist src\tests\testNetWork\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\tests\testNetWork\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\tests\testNetWork\testNetWork.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
sub-src-examples-testPlugin-testPlugin-pro-benchmark:
	@if not exist src\examples\testPlugin\ mkdir src\examples\testPlugin\ & if not exist src\examples\testPlugin\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\examples\testPlugin\ && ( if not exist Makefile $(QMAKE) E:\Projects\VS2013\QAF\src\examples\testPlugin\testPlugin.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile benchmark
benchmark: sub-src-NetWork-NetWork-pro-benchmark sub-src-DBManager-DBManager-pro-benchmark sub-src-QtAwesome-QtAwesome-pro-benchmark sub-src-QtCommonModel-QtCommonModel-pro-benchmark sub-src-Utils-Utils-pro-benchmark sub-src-QAFCore-QAFCore-pro-benchmark sub-src-QAF-QAF-pro-benchmark sub-src-UIPlugin-UIPlugin-pro-benchmark sub-src-tests-testNetWork-testNetWork-pro-benchmark sub-src-examples-testPlugin-testPlugin-pro-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

