# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = QtAwesome
QT += core widgets gui
CONFIG += debug_and_release

DEFINES += QT_DLL QTAWESONME_LIB
INCLUDEPATH += $$PWD \
    $$PWD/../Utils \
    $$PWD/../../include \

include($$PWD/../Common.pri)
include(QtAwesome.pri)
