# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = QtAwesome
DESTDIR = $$PWD/../../output/lib
QT += core widgets gui
CONFIG += debug_and_release
TARGET = $$qtLibraryTarget($$TARGET)

DEFINES += QT_DLL QTAWESONME_LIB
INCLUDEPATH += $$PWD \
    $$PWD/../Utils \
    $$PWD/../../include \

#LIBS += -l$(NOINHERIT)
DEPENDPATH += $$PWD

include(QtAwesome.pri)
