# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = Utils
DESTDIR = ../../lib
QT += core
CONFIG += debug_and_release
DEFINES += QT_DLL UTILS_LIB
INCLUDEPATH += .
DEPENDPATH += .
CONFIG(debug,debug|release){
    TARGET=$$join(TARGET,,,d)
}

CONFIG(release,release|debug){

}
include(Utils.pri)
