# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = Utils
DESTDIR = $$PWD/../../output/lib
QT += core
CONFIG += debug_and_release
DEFINES += QT_DLL UTILS_LIB
INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD
CONFIG(debug,debug|release){
    unix:TARGET=$$join(TARGET,,,_debug)
    else:TARGET=$$join(TARGET,,,d)
}

include(Utils.pri)
