# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = QtCommonModel

DESTDIR = $$PWD/../../output/lib
QT += core
CONFIG += debug_and_release c++11
TARGET = $$qtLibraryTarget($$TARGET)

DEFINES += QT_DLL QTCOMMONMODEL_LIB
INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD

include(QtCommonModel.pri)
