#ifndef QTCOMMONMODEL_GLOBAL_H
#define QTCOMMONMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QTCOMMONMODEL_LIB
# define QTCOMMONMODEL_EXPORT Q_DECL_EXPORT
#else
# define QTCOMMONMODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCOMMONMODEL_GLOBAL_H
