# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = DBManager
DESTDIR = ../../lib
QT += core sql
CONFIG += debug_and_release
DEFINES += QT_DLL DBMANAGER_LIB QT_SQL_LIB
DEPENDPATH += .
CONFIG(debug,debug|release){
    TARGET=$$join(TARGET,,,d)
}
CONFIG(release,release|debug){

}
include(DBManager.pri)

message($$ConfigureName)
