# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = DBManager
QT += core sql
CONFIG += debug_and_release

DEFINES += QT_DLL DBMANAGER_LIB QT_SQL_LIB
DEPENDPATH += $$PWD

include($$PWD/../Common.pri)
DESTDIR = $$PWD/../../output/lib/$$PLATFORM

#deploy.commands =
#QMAKE_EXTRA_TARGETS += deploy

include(DBManager.pri)
