# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = testNetWork
DESTDIR = ../../../bin/Debug
QT += core network testlib
CONFIG += debug_and_release console
DEFINES += QT_DLL QT_TESTLIB_LIB
INCLUDEPATH += . \
    ./../../NetWork \
    ./../../Utils
LIBS += -L"./../../../lib"
DEPENDPATH += .
CONFIG(debug,debug|release){
    TARGET=$$join(TARGET,,,d)
    LIBS += -lNetWorkd
}

CONFIG(release,release|debug){
    LIBS += -lNetWork
}
include(testNetWork.pri)
