# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = testNetWork
win32:DESTDIR = $$PWD/../../../bin/win32
unix:DESTDIR = $$PWD/../../../bin/unix
QT += core network testlib
CONFIG += debug_and_release console
DEFINES += QT_DLL QT_TESTLIB_LIB
INCLUDEPATH += $$PWD \
    $$PWD/../../NetWork \
    $$PWD/../../Utils

LIBS += -L"$$PWD/../../../lib"
DEPENDPATH += $$PWD
CONFIG(debug,debug|release){
    win32:TARGET=$$join(TARGET,,,d)
    unix:TARGET=$$join(TARGET,,,_debug)
    LIBS += -lNetWorkd
}

CONFIG(release,release|debug){
    LIBS += -lNetWork
}
include(testNetWork.pri)
